teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 5
    scale_linear:
      x: 0.2
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 4
    scale_angular:
      yaw: 0.4

    enable_button: 5  # L2 shoulder button
    enable_turbo_button: 4  # L1 shoulder button
